### ISSUE TITLE
Fix `NumberDataValidator` exception on string input

### ISSUE THREAD

**Issue by nico-oculusd** [oculusd/odc_pycommons#12]
Test:

```python
>>> from odc_pycommons.security import *
>>> from decimal import Decimal
>>> number_validator = NumberDataValidator()
>>> num1 = 123
>>> num2 = 123.45
>>> num3 = Decimal(22/7)
>>> num3
Decimal('3.142857142857142793701541449991054832935333251953125')
>>> num4 = '99.00'
>>> num5 = '$1.00'
>>> for num in (num1, num2, num3, num4, num5):
...     print('Input value "{}" of type {} is a number: {}'.format(num, type(num), number_validator.validate(num)))
...
Input value "123" of type <class 'int'> is a number: True
Input value "123.45" of type <class 'float'> is a number: True
Input value "3.142857142857142793701541449991054832935333251953125" of type <class 'decimal.Decimal'> is a number: True
Input value "99.00" of type <class 'str'> is a number: True
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\git\odc_pycommons\odc_pycommons\security.py", line 215, in validate
    return self._validate_str(data=data, **kwarg)
  File "D:\git\odc_pycommons\odc_pycommons\security.py", line 196, in _validate_str
    return self._validate_decimal(data=Decimal(data), **params)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
>>>
```

**Comment by nico-oculusd** [comment]
Fixed:

```python
>>> from odc_pycommons.security import *
>>> number_validator = NumberDataValidator()
>>> num3 = Decimal(22/7)
>>> num5 = '$1.00'
>>> number_validator.validate(num3)
True
>>> number_validator.validate(num5)
2019-04-24 15:09:27,404 - ERROR - Input value "$1.00" could not be converted to a number format for verification.
False
>>> num4 = '99'
>>> number_validator.validate(num4)
True
>>> num4 = '99.123'
>>> number_validator.validate(num4)
True
>>> num4 = '99%'
>>> number_validator.validate(num4)
2019-04-24 15:10:04,576 - ERROR - Input value "99%" could not be converted to a number format for verification.
False
```
